// GENERATED by scripts/ingest-web.mts — do not edit by hand. Re-run: npm run ingest:web
//
// Product information ingested from prudential.com.sg, as retrievable clauses. Kept separate from
// the hand-authored brochure clauses so the source is always visible: these carry a "(web)" document
// and cite the page URL, and the comprehension spine (concepts, the suitability figures) stays
// anchored to the brochure, never to a marketing page.
import type { Clause } from "./knowledge";

export const WEB_KNOWLEDGE: Clause[] = [
  {
    "id": "web-prushield-1",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Health coverage that shelters you, just like home. PRU Shield is a MediSave-approved Integrated Shield Plan that goes beyond providing access to affordable and quality healthcare – it's about ensuring peace of mind for you and your loved ones. Enjoy 15% off first-year premium * when you make the switch with PRU Shield EasySwitch from now till 30 September 2026. Enjoy the seamless transition with continued coverage and simplified sign-up today! Public Service Officers and their dependents can enjoy 10% off PRU Shield Premier and PRU Shield Plus premiums for the first year. Designed to complement your MediShield Life (for Singaporeans and Permanent Residents), PRU Shield offers the option to pay your premiums with your Medisave (up to the Additional Withdrawal Limits)."
  },
  {
    "id": "web-prushield-2",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "PRU Shield is also available for foreigners as a private health insurance plan, making it a versatile choice for individuals seeking medical insurance in Singapore. Supplement your PRU Shield plan with PRU Extra PRU Extra is a supplementary plan that provides an extra level of protection. Combined with PRU Shield, you'll enjoy more comprehensive health insurance coverage plus access to Value-Added Services (where applicable) on top of your existing coverage with MediShield Life."
  },
  {
    "id": "web-prushield-3",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Following the announcement by Ministry of Health (MOH) on the enhancements to Integrated Shield Plan (IP) riders, Prudential will be complying with the requirements of introducing new PRU Extra supplementary plans with adjustments to deductible coverage and stop-loss benefit from 1 April 2026. PRU Extra supplementary plan that is submitted from 27 November 2025 to 31 March 2026 (both dates inclusive) must transition to the new supplementary plan that meet the new requirements upon their next policy renewal from 1 April 2028 onwards. For more information, please refer to the Frequently Asked Questions . Changes effective from 1 April 2026 and 1 May 2026 Enhancement of Stem Cell Transplant Treatment Benefit"
  },
  {
    "id": "web-prushield-4",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Addition of Outpatient and Home-Based Benefits Updates to the Cell, Tissue and Gene Therapy Treatment and High-Cost Drugs (non-cancer) Benefits B. Changes to your PRUExtra Supplementary Plan Addition of coverage for Non-Listed Cell, Tissue and Gene Therapy Products Enhancement of Claims-Based Premium Pricing for Extended Panel (Panel Healthcare Institution) Effective upon policy renewal from 1 May 2026 for selected existing plans The premium rates for PRU Shield and PRU Extra Supplementary plans will be adjusted as part of our regular review. This reflects the increase in healthcare costs and claims in recent years. Effective from 1 April 2026 for new policies ( PRU Shield only), and upon policy renewal from 1 April 2026 for existing plans:"
  },
  {
    "id": "web-prushield-5",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Effective upon policy renewal from 1 May 2026 for existing plans: D. PRUExtra Supplementary Plan Options available for Plan Upgrade and Downgrade From 1 April 2026 , three new PRU Extra supplementary plans will be available: PRU Extra Premier Care, PRU Extra Preferred Care and PRU Extra Plus Care . Plan upgrades and downgrades will only be available into these new PRU Extra Care supplementary plans. Please note that plan upgrades are subject to medical underwriting. For detailed information regarding previous updates to PRU Shield, please refer to our Notices page or Frequently Asked Questions . MediShield Life covers a basic level of medical expenses for Singaporeans and PRs. PRU Shield and PRU Extra complement MediShield Life to give you enhanced coverage and lower out-of-pocket expenses."
  },
  {
    "id": "web-prushield-6",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "* Deductible: The amount you need to pay before any PRU Shield benefits are paid out. ** Co-insurance: A percentage of the claimable amount you need to co-pay or share after you have paid for the Deductible. Up to S$2 million 1 including cancer treatment and risk-based loading 2 Comprehensive outpatient cancer treatment coverage Change to 20x MSHL for one primary cancer 3 Up to 180 days and up to 365 days, respectively Smooth hospitalisation with Value-Added Services (where applicable) such as Pre-Authorisation, applicable to PRU Shield customers We believe planning your healthcare should be simple. Choosing what you need should not take more than 4 clicks. What level of health services are you looking for?"
  },
  {
    "id": "web-prushield-7",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "What is your preference level for privacy? I prefer to be exclusive, with my own room I am comfortable sharing a room with 3 other people Would you like to pay for additional coverage on your deductibles and co-insurance Yes, because I’m investing for peace of mind I want the best and nothing but the best I'd like to have the best of both worlds. Good quality, yet affordable I only want to pay for what I need and nothing more, no frills style I’d like access to all private hospitals. I’m ok to choose from a list of private hospitals at a lower premium. Would you like to pay for additional coverage on your co-insurance No thanks. I don't need additional coverage. Do you prefer wider coverage on deductible amount?"
  },
  {
    "id": "web-prushield-8",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "I prefer wider coverage on deductible amount I’m good with lesser coverage on deductible amount Would you like to pay for additional coverage on your co-insurance No thanks, I don’t need additional coverage Which healthcare providers do you prefer to seek treatment from? I’d like the options to visit all providers in Singapore I’d only be able to use Panel & Non-Panel providers Covers B1 ward in public hospitals and below. Covers standard rooms in private hospitals Covers A ward in public hospitals and below. Further lowers your out-of-pocket expenses* at public hospitals Covers A ward in public hospitals and below. Basic, no-frills private hospital option to further lower part of your out-of-pocket expenses* at all private and public hospitals in Singapore"
  },
  {
    "id": "web-prushield-9",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Covers standard rooms in private and all public hospitals. ”Best of the best\" option to further lower your out-of-pocket expenses* at all private and public hospitals in Singapore Value-added services including cashless hospitalisation and concierge services The highest premium solution for your protection needs Covers standard rooms in private and all public hospitals. ”Value-for-money\" option to further lower your out-of-pocket expenses* at selected private hospitals and all public hospitals in Singapore, at a more affordable rate Value-added services including cashless hospitalisation and concierge services Covers A ward in public hospitals and below. Further lowers your out-of-pocket expenses* at public hospitals"
  },
  {
    "id": "web-prushield-10",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Covers standard rooms in private and all public hospitals “Best of the best” option to further lower your out-of-pocket expenses* at all private and public hospitals in Singapore Value-added services including cashless hospitalization and concierge services Our comprehensive solution for your protection needs Covers A ward in public hospitals and below Further lowers your out-of-pocket expenses* at public hospitals Covers standard rooms in private and all public hospitals \"Value-for-money\" option to further lower your out-of-pocket expenses* at selected private hospitals and all public hospitals in Singapore, at a more affordable rate Value-added services including cashless hospitalisation and concierge services"
  },
  {
    "id": "web-prushield-11",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Your out-of-pocket expenses will include your deductible and co-insurance. Your deductible is the fixed amount you have the pay of the bill before any benefit is payable. The deductible ranges from S$1,500 - S$3,500 depending on age and ward class. Your co-insurance is the percentage of the bill that you have to pay after the deductible is paid. The maximum co-insurance is 10%. What You Need to Pay if You are Hospitalised Understand how PRU Shield Standard ^ complements your existing medical coverage and lowers your out-of-pocket expenses. Note: This is for illustrative purposes only. Please refer to PRU Shield Brochure for more details. Assuming policy holder is a Singaporean below 80 years old, and treatment was sought at a panel private hospital with a medical bill of S$50,000."
  },
  {
    "id": "web-prushield-12",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "MediShield Life and PRU Shield Standard covers What You Need to Pay if You are Hospitalised With PRU Shield Plus, you have the option to add on PRU Extra Plus Care for greater protection. Understand how these plans complement your existing medical coverage and lowers your out-of-pocket expenses. Note: This is for illustrative purposes only. Please refer to PRU Shield Brochure for more details. Assuming policy holder is a Singaporean below 80 years old, and treatment was sought at a panel private hospital with a medical bill of S$50,000. With PRU Shield Plus and PRU Extra Plus Care Supplementary Plan MediShield Life and PRUShield Plus covers Your out-of-pocket expenses will be S$0.00 Assuming policy holder is a Singaporean below 80 years old, and treatment was sought at a restructured hospital with a medical bill of S$50,000."
  },
  {
    "id": "web-prushield-13",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "With PRU Shield Plus and PRU Extra Plus Care Supplementary Plan MediShield Life and PRUShield Plus covers Your out-of-pocket expenses will be S$0.00 A supplementary plan that provides an extra level of protection, PRU Extra enhances your existing PRU Shield plan so you can enjoy an even more comprehensive coverage. Medical and surgical expenses at restructured hospitals (up to class A wards) 4 Covers 95% of the deductible 4 amount above S$3,500 under panel and non-panel providers 5 Receive up 15x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Treatment (on the Cancer Drug List) 7 Receive up 15x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Services 8"
  },
  {
    "id": "web-prushield-14",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Receive S$150,000 per policy year for Cancer Drug Treatment (not on CDL) S$6,000 stop-loss per policy year (exclude deductible) 9 Medical and surgical expenses at restructured hospitals (up to class A wards) 4 Covers 95% of the deductible 4 amount above S$3,500 under panel and non-panel providers 5 Receive up 15x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Treatment (on the Cancer Drug List) 7 Receive up 15x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Services 8 Receive S$150,000 per policy year for Cancer Drug Treatment (not on CDL) S$6,000 stop-loss per policy year (exclude deductible) 9 Premiums of Supplementary Plan for aged 30 12"
  },
  {
    "id": "web-prushield-15",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "For customers who currently have any of the following withdrawn riders, please click here for detailed information about your coverage. What You Need to Pay if You are Hospitalised With PRU Shield Premier, you have the option to add on to PRU Extra Premier Care or PRU Extra Preferred Care Supplementary Plan for greater protection. Understand how these plans complement your existing medical coverage and lowers your out-of-pocket expenses. Note: This is for illustrative purposes only. Please refer to PRU Shield Brochure for more details. Assuming policy holder is a Singaporean below 80 years old, and treatment was sought at a panel private hospital with a medical bill of S$50,000. With PRU Shield Premier and PRU Extra Premier Care Supplementary Plan"
  },
  {
    "id": "web-prushield-16",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "MediShield Life and PRUShield Premier covers With PRU Shield Premier and PRU Extra Preferred Care Supplementary Plan MediShield Life and PRUShield Premier covers Your out-of-pocket expenses will be S$0.00 A supplementary plan that provides an extra level of protection, PRU Extra enhances your existing PRU Shield plan so you can enjoy an even more comprehensive coverage. Medical and surgical expenses at restructured and private hospitals Covers 95% of the deductible 4 amount above S$3,500 under panel and non-panel providers 5 Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Treatment (on the Cancer Drug List) 7 Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Services 8"
  },
  {
    "id": "web-prushield-17",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Receive S$150,000 per policy year for Cancer Drug Treatment (not on CDL) S$6,000 stop-loss per policy year (exclude deductible) 9 Additional S$100,000 policy year limit when hospitalised due to Early to Late Critical Illness S$150,000 for one treatment per clinical indication per lifetime with 10% co-insurance for Non-Listed Cell Tissue and Gene Therapy Treatment (CTGTP) Benefit Singapore Private Hospitals under our Panel or Non-Panel Providers 5 Medical and surgical expenses at restructured and private hospitals Covers 95% of the deductible 4 amount above S$3,500 under panel and non-panel providers 5 Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Treatment (on the Cancer Drug List) 7"
  },
  {
    "id": "web-prushield-18",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Services 8 Receive S$150,000 per policy year for Cancer Drug Treatment (not on CDL) S$6,000 stop-loss per policy year (exclude deductible) 9 Additional S$100,000 policy year limit when hospitalised due to Early to Late Critical Illness S$150,000 for one treatment per clinical indication per lifetime with 10% co-insurance for Non-Listed Cell Tissue and Gene Therapy Treatment (CTGTP) Benefit Premiums of Supplementary Plan for aged 30 12 Covers 95% of the deductible 4 amount above S$3,500 under panel and non-panel providers 5 PRU Extra Preferred Care co-insurance is not applicable for non-panel providers)"
  },
  {
    "id": "web-prushield-19",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Treatment (on the Cancer Drug List) 7 Receive up 20x of the MediShield Life limit for one primary cancer per month to receive on Cancer Drug Services 8 Receive S$150,000 per policy year for Cancer Drug Treatment (not on CDL) S$6,000 stop-loss per policy year (exclude deductible) 9 Additional S$100,000 policy year limit when hospitalised due to Early to Late Critical Illness S$150,000 for one treatment per clinical indication per lifetime with 10% co-insurance for Non-Listed Cell Tissue and Gene Therapy Treatment (CTGTP) Benefit Singapore Private Hospitals under our Panel or Non-Panel Providers 5"
  },
  {
    "id": "web-prushield-20",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Premiums of Supplementary Plan for aged 30 12 For customers who currently have any of the following withdrawn riders, please click here for detailed information about your coverage. Additional benefits for PRU Extra Premier Care and PRU Extra Preferred Care customers Get access to a suite of exclusive services and benefits that simplify your healthcare journey. PRU Panel Connect services are exclusively available for: Visit our PRU Concierge at partner private hospitals at Raffles Hospital, Mount Alvernia Hospital and Thomson Medical Centre for exclusive value-added services and assistance on any PRU Shield related enquiries, including PRU Shield Recovery. Simply make a booking by emailing us at prupanel.connect@prudential.com.sg or call our PRU Customer line at 1800 333 0333. Find a PRU Panel Connect Specialist here ."
  },
  {
    "id": "web-prushield-21",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Eligible policyholders get a higher eLOG amount and cashless experience at select medical institutions 14 . Claims-based premium pricing lets you enjoy 20% off 15 on your Standard Level Premium when your policy is accepted by us without any special terms and conditions. Exclusive Value-Added Services for All PRU Shield customers In today's fast-paced world, staying healthy can be challenging. That's why we have partnered with leading healthcare networks to provide you with the best tools and support. All PRU Shield policyholders are also eligible to enjoy hassle-free Pre-Authorisation online submission . Teleconsultation fee of S$13 (excl. GST) from 6am to 8.59pm and S$28 (excl. GST) from 9pm to 5.59am 16"
  },
  {
    "id": "web-prushield-22",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Medication delivered within 3 hours with no delivery fees 17 Appointment to see a panel specialist within 3 working days 18 All PRU Shield customers will enjoy on-site general practitioner (GP) consultations at a partner rate of S$13 19 (excluding GST) at over 400 GP clinics islandwide in Singapore PRU Shield customers can enjoy partner rates by registering with Doctor Anywhere (DA) via PRU Services to obtain a DA eCard, presenting the eCard at the participating clinic, and making payment via DA Pay in the mobile app. Get referred to PRU Panel Connect specialists directly from your GP visit (if required) Basic health screening packages and vaccination services starting from S$74 Fully subsidised home-based child (2 – 18 months) and senior (65 years and above 20 ) vaccination"
  },
  {
    "id": "web-prushield-23",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Referral to a panel specialist is available if you require a follow-up Preventive screenings at any of the 37 Raffles Medical clinics islandwide at no cost with convenient online appointment booking Mental health assessments with a PHQ-9 at no cost Consists of tests for Diabetes , Hypertension , High Cholesterol (Hyperlipidemia) and Mental Wellness A suite of exclusive Value Added Services including expedited appointment bookings, cashless transactions 21 concierge services at partner private hospitals, higher electronic Letter of Guarantee (eLOG) and more at our Participating hospitals/Day surgery centres and specialists. Only for PRUShield Premier customer with PRUExtra Premier Care and Preferred Care"
  },
  {
    "id": "web-prushield-24",
    "source": "PRUShield & PRUExtra (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/medical/prushield",
    "text": "Coverage of Cancer Drug Treatment and Cancer Drug Service The Ministry of Health (MOH) has released new guidelines on the cancer drug treatments that can be covered by Integrated Shield Plans. As part of efforts to reduce the cost of cancer drug treatment and keep premiums sustainable in the long-term, MOH has developed a Cancer Drug List (CDL). The CDL comprises clinically proven and more cost-effective cancer drug treatments (i.e., drugs paired with specified clinical indications, dosage form & strength, for which the drugs can be administered). From 1 September 2022, only cancer drug treatment that are listed on the CDL and administered as per the CDL will be claimable from MediShield Life (MSHL) and MediSave (MSV). For Integrated Shield Plans (including PRUShield), the same change will take effect for policies renewed or purchased on or after 1 April 2023."
  },
  {
    "id": "web-pruactive-protect-1",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Sometimes in life a sudden critical illness can throw you off track, leaving you concerned about looking after your loved ones, especially if it unfortunately happens more than once. PRU Active Protect is a customisable critical illness insurance plan that supports you during difficult times. The plan is designed to grow with you through life. Find out more in our Build to Grow video. PRU Active Protect is a customisable critical illness insurance plan that allows you to choose a policy term from 10 years up to 99 years and get critical illness coverage against 37 life-threatening illnesses up to age 100. It can continue to protect you for repeated illnesses, right from diagnosis. The plan is designed to grow with you through life by providing you with the flexible option to add on coverage against pre-critical stage, recurring and relapse critical illness conditions and more, as and when your needs, priorities and budget grows."
  },
  {
    "id": "web-pruactive-protect-2",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Customise your critical illness protection with supplementary benefits that you can add anytime 1 . Receive 50% of your critical illness coverage on serious illnesses or accidents that result in major surgery on vital organs and admission to the Intensive Care Unit (ICU) 2 . Opt to build more comprehensive coverage against relapse, recurrence of pre-critical or late stage critical illness conditions and more. Complimentary protection for your children against 36 critical illnesses and 9 juvenile conditions 3 when both parents purchase PRU Active Protect. Claim up to 500% 4 of your basic critical illness coverage by restoring your basic critical illness coverage to 100% after a critical illness benefit claim."
  },
  {
    "id": "web-pruactive-protect-3",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Get coverage against all pre-critical stage critical illnesses and receive a lump sum payout upon pre-critical stage critical illness diagnosis 5 . Claim up to 500% of your Early Protect sum assured by restoring your Early Protect sum assured to 100% after a pre-critical stage critical illness benefit claim 6 . Receive an additional lump-sum payout, of up to 100% of your basic critical illness coverage, upon death 7 . An additional lump sum payout when you are diagnosed with a serious infectious disease 8 and is admitted to ICU for 5 or more consecutive days because of the infection. Receive monthly payouts 9 between S$100 to S$5,000 for a period of either 1, 2 or 3 years on top of your lump sum payout when diagnosed with a critical illness."
  },
  {
    "id": "web-pruactive-protect-4",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Supplementary benefits can only be added during the policy term of PRU Active Protect upon satisfying the minimum policy term of the respective supplementary benefit. Full medical underwriting applies at the point of application of these supplementary benefits. Applicable only when insured undergoes surgery of any of the vital organs (heart, lung, brain, kidney, liver) as a result of illness or accident and as a result of the surgery, the insured is admitted to ICU for 3 consecutive days or more. Excluding surgery due to organ donation. Subject to cap of S$100,000 per life assured. Only 1 claim is payable per policy. Child Cover Benefit is 25% of one of the parents’ PRU Active Protect sum assured, whichever is higher. Payable only once for each child and up to S$25,000 for each child."
  },
  {
    "id": "web-pruactive-protect-5",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Subject to maximum of 500% of the PRU Active Protect sum assured. This 500% includes claims for any of the pre-critical stage illness under the Early Protect benefit (if the benefit is included). For Prudential to accept the next claim, the following must apply: For recurring critical illness condition under different categories, there must be a period of 12 months between the dates of diagnosis (waiting period). For recurring critical illness condition under the same category, there must be a waiting period of 24 months between the dates of diagnosis. The medical evidence must clearly show that the initial or previous critical illness condition (which has been admitted) was already in complete remission before the recurring critical illness condition was diagnosed"
  },
  {
    "id": "web-pruactive-protect-6",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "The total amount payable depends on the number of claims made. The amount payable for each claim is subject to the maximum per claim limit and is based on the terms and conditions listed in the Product Summary. Please speak to your Prudential Financial Consultant for more details. Payout for Early Protect accelerates the critical illness benefit and will reduce the PRU Active Protect sum assured. Once claimed, the Early Protect benefit terminates (if there is no Early Protect Plus attached). Subject to maximum of 500% of the Early Protect sum assured. This 500% includes claims for any of the critical illness under the PRU Active Protect policy. For Prudential to accept the next claim, the following must apply:"
  },
  {
    "id": "web-pruactive-protect-7",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "For recurring critical illness condition under different categories, there must be a waiting period of 12 months between the dates of diagnosis. For recurring critical illness condition under the same category, there must be a waiting period of 24 months between the dates of diagnosis. The medical evidence must clearly show that the initial or previous critical illness condition (which has been admitted) was already in complete remission before the recurring critical illness condition was diagnosed The total amount payable depends on the number of claims made. The amount payable for each claim is subject to the maximum per claim limit and is based on the terms and conditions listed in the Product Summary. Please speak to your Prudential Financial Consultant for more details."
  },
  {
    "id": "web-pruactive-protect-8",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "Sum assured of Life Protect Plus must be equal or lower than the PRU Active Protect sum assured. Sum assured of Severe Infections Protect must be equal or lower than the PRU Active Protect sum assured and subject to a maximum of S$100,000. Payable once on the first critical illness benefit claim only. You are recommended to read the product summary and seek advice from a qualified Prudential Financial Representative, or a distributor duly appointed by Prudential Singapore for a financial analysis before purchasing a policy suitable to meet your needs. As this product has no savings or investment feature, there is no cash value if the policy ends or if the policy is terminated prematurely. Buying health insurance products that are not suitable for you may impact your ability to finance your future healthcare needs. Premiums are not guaranteed and may be adjusted based on future claims experience."
  },
  {
    "id": "web-pruactive-protect-9",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "As buying a life insurance policy is a long-term commitment, an early termination of the policy usually involves high costs and the surrender value, if any, that is payable to you may be zero or less than the total premiums paid. The information on this website is for reference only and is not a contract of insurance. Please refer to the exact terms and conditions, specific details and exclusions applicable to this insurance product in the policy documents which can be obtained from your Prudential Financial Representative. The information contained on this website is intended to be valid in Singapore only and shall not be construed as an offer to sell or solicitation to buy or provision of any insurance product outside Singapore."
  },
  {
    "id": "web-pruactive-protect-10",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "In case of discrepancy between the English and Mandarin versions of the product brochures, the English version shall prevail. These policies are protected under the Policy Owners’ Protection Scheme which is administered by the Singapore Deposit Insurance Corporation (SDIC). Coverage for your policy is automatic and no further action is required from you. For more information on the types of benefits that are covered under the scheme as well as the limits of coverage, where applicable, please contact your insurer or visit the GIA/LIA or SDIC websites ( www.gia.org.sg or www.lia.org.sg or www.sdic.org.sg ). Information is correct as of 1 December 2025. This advertisement has not been reviewed by the Monetary Authority of Singapore."
  },
  {
    "id": "web-pruactive-protect-11",
    "source": "PRUActive Protect (prudential.com.sg) · https://www.prudential.com.sg/products/health-insurance/critical-illness/pruactive-protect",
    "text": "An affordable cancer insurance plan that provides multi-stage coverage against all cancers. A unique health insurance plan tailored for women against female-specific critical illnesses. A unique health insurance plan tailored for men against male-specific critical illnesses. Imagine living in a world without insurance 3 easy ways to improve your family’s health A healthy lifestyle comprising a balanced and nutritious diet coupled with regular exercise is a winning combination that will help keep your family fit and happy. Here are 4 important insurance plans to consider for your family For most of us, family means the world. As such, you would want to take every measure to ensure that they stay protected against the many uncertainties in life."
  }
];

// Web document → product area, so retrieval scopes these the same way brochure clauses are scoped.
export const WEB_DOCUMENT_AREA: Record<string, string> = {
  "PRUShield & PRUExtra (prudential.com.sg)": "Health Protection",
  "PRUActive Protect (prudential.com.sg)": "Critical Illness"
};
